on:
  schedule:
    - cron: "5 0 * * 0"
  workflow_dispatch:

jobs:
  push_to_registries:
    name: Build and Push Container
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: 'Login to Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecs_service_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          podman build \
            --label "org.opencontainers.image.source=https://auyer/arch-yay-container" \
            --label "org.opencontainers.image.description=Weekly build of the Arch container with `yay` AUR Helper pre installed" \
            --label "org.opencontainers.image.licenses=MIT" \
            -t ghcr.io/auyer/arch-yay-container:latest .
          podman tag ghcr.io/auyer/arch-yay-container:latest ghcr.io/auyer/arch-yay-container:$(date +'%Y%-m%d')
          podman push ghcr.io/auyer/arch-yay-container:$(date +'%Y%-m%d')
          podman push ghcr.io/auyer/arch-yay-container:latest
          echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" > image.txt


